### ISSUE TITLE
Build SUCHAI project

### ISSUE THREAD

**Issue by osqzss** [spel-uchile/SUCHAI#25]
Which versions of the MPLAB X IDE and XC16 compiler are required to build the SUCHAI project with the FreeRTOS and legacy PIC24 peripheral library?

**Comment by joseogalde** [comment]
I recently build the project with MPLAB X IDE v3.30, XC16 v1.24 and programed to a PIC24FJ256GA110. The version 1.26 of the XC16 compiler didn't work.

**Comment by osqzss** [comment]
The project has been built successfully with the tools that you mentioned. Thank you.
Another quick question. I'm wondering which peripheral device is used for "printf" function 
and where it is specified.

**Comment by carlgonz** [comment]
We're using the UART1 module. For the PIC24 I defined the `mon_putc` function in main.c line 143. At the end, `printf` internally call `mon_putc`. See: https://github.com/spel-uchile/SUCHAI/blob/3d88d9bd2087b6a5a49a2679c8ac0b97544706cd/main.c#L143

**Comment by osqzss** [comment]
Thanks for the tip. Now I can understand that you override the write() function in libc. That's a neat hack.

**Comment by carlgonz** [comment]
You're welcome!
